version : "3.3"
services:
 mysqldb:
  container_name: mysqldb1
  image: mysql:8
  restart: unless-stopped
  environment:
   MYSQL_ROOT_PASSWORD: root
  volumes:
    -db_data:/var/lib/mysql
 spring_app:
  image: rihabhn/backendappimage
  container_name: backendapp
  restart: on-failure
  ports:
   - 8089:8089
  depends_on:     
   - mysqldb
   volumes: 
    db_data
    
